[package]
name = "drew-physics"
version = "0.2.0"
edition = "2024"
authors = ["Jorge Andre Castro"]
description = "Moteur de simulation physique 2D agnostique, no_std, sans allocation et optimisé f32"
license = "GPL-2.0-or-later"
repository = "https://github.com/jorgeandrecastro/drew-physics"
readme = "README.md"
keywords = ["physics", "2d", "no_std", "game-development", "simulation"]
categories = ["game-engines", "no-std", "science"]
documentation = "https://docs.rs/drew-physics"

[lib]
name = "drew_physics"
path = "src/lib.rs"

[[example]]
name = "simulation"
path = "examples/simulation.rs"

[dependencies]
embedded-f32-sqrt = "0.2.0"

[dev-dependencies]
bevy = "0.19" 

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true